import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Github, Sparkles, Target, Share2 } from "lucide-react";

export default function HomePage() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
            <div className="container mx-auto px-4 py-24">
                <div className="max-w-4xl mx-auto text-center space-y-12">
                    <div className="space-y-4">
                        <h1 className="text-6xl md:text-7xl font-bold tracking-tight bg-gradient-to-r from-primary via-purple-600 to-blue-600 bg-clip-text text-transparent">
                            DevShowcase
                        </h1>
                        <p className="text-2xl md:text-3xl font-medium text-muted-foreground">
                            Stop telling. Start showing.
                        </p>
                    </div>

                    <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
                        The AI-powered platform that analyzes your real projects, asks intelligent questions, and generates verified skill scorecards you can share anywhere.
                    </p>

                    <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8">
                        <Button size="lg" className="text-lg px-8 py-6 h-auto" asChild>
                            <Link href="/new-project">
                                Get Started <Sparkles className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                        <Button size="lg" variant="outline" className="text-lg px-8 py-6 h-auto" asChild>
                            <Link href="https://github.com/Rish3666/EvalHub" target="_blank">
                                View on GitHub <Github className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                    </div>

                    <div className="grid md:grid-cols-3 gap-8 pt-24 text-left">
                        <div className="p-6 bg-card border rounded-2xl space-y-4 shadow-sm">
                            <div className="p-3 bg-primary/10 rounded-xl w-fit">
                                <Sparkles className="h-6 w-6 text-primary" />
                            </div>
                            <h3 className="text-xl font-bold">AI Deep Dive</h3>
                            <p className="text-muted-foreground">Our AI analyzes your code and README to understand the technical depth of your work.</p>
                        </div>
                        <div className="p-6 bg-card border rounded-2xl space-y-4 shadow-sm">
                            <div className="p-3 bg-purple-100 rounded-xl w-fit">
                                <Target className="h-6 w-6 text-purple-600" />
                            </div>
                            <h3 className="text-xl font-bold">Smart Assessment</h3>
                            <p className="text-muted-foreground">Answer project-specific questions generated by AI to prove your technical expertise.</p>
                        </div>
                        <div className="p-6 bg-card border rounded-2xl space-y-4 shadow-sm">
                            <div className="p-3 bg-blue-100 rounded-xl w-fit">
                                <Share2 className="h-6 w-6 text-blue-600" />
                            </div>
                            <h3 className="text-xl font-bold">Shareable Proof</h3>
                            <p className="text-muted-foreground">Get a verified skill scorecard with a shareable URL and dynamic OG images for social media.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
