'use client';

import {
    Card,
    CardHeader,
    CardTitle,
    CardContent,
} from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
    Target,
    TrendingUp,
    AlertTriangle,
    Lightbulb,
    CheckCircle2,
    ArrowUpRight,
} from 'lucide-react';
import { getScoreColor, getPriorityColor } from '@/lib/utils';

interface ScorecardProps {
    scorecard: {
        overall_score: number;
        skill_breakdown: Record<
            string,
            { score: number; level: string; evidence: string }
        >;
        technologies_known: Array<{
            name: string;
            proficiency: string;
            percentage: number;
            evidence: string;
        }>;
        skill_gaps: Array<{
            skill: string;
            reason: string;
            priority: string;
            learningPath: {
                beginner: string;
                intermediate: string;
                projectIdea: string;
            };
        }>;
        recommendations: string[];
        strengths: string[];
        areas_for_improvement: string[];
    };
    project: {
        title: string;
        author: { full_name: string };
    };
}

export function ScorecardDisplay({ scorecard, project }: ScorecardProps) {
    return (
        <div className="flex flex-col min-h-screen">
            {/* Header */}
            <div className="sticky top-0 z-10 bg-background/80 backdrop-blur-md px-4 py-3 border-b border-border/50 transition-all">
                <div className="flex items-center gap-4">
                    <h1 className="text-xl font-bold">Analysis Results</h1>
                </div>
            </div>

            <div className="px-4 py-6 space-y-6">
                <div className="space-y-1">
                    <h2 className="text-2xl font-black italic tracking-tighter uppercase">{project.title}</h2>
                    <p className="text-muted-foreground text-sm font-medium">
                        by {project.author.full_name} · Generated by EvalHub AI
                    </p>
                </div>

                {/* Overall Score */}
                <Card className="bg-primary/5 border-primary/20">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="flex items-center gap-2">
                                <Target className="h-6 w-6 text-primary" />
                                <span className="text-lg font-bold">
                                    Overall Technical Score
                                </span>
                            </div>
                            <div
                                className={`text-4xl font-black ${getScoreColor(
                                    scorecard.overall_score
                                )}`}
                            >
                                {scorecard.overall_score}<span className="text-xl opacity-50">/100</span>
                            </div>
                        </div>
                        <Progress value={scorecard.overall_score} className="h-2 bg-primary/10" />
                    </CardContent>
                </Card>

                {/* Skill Breakdown */}
                <Card>
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-2 text-xl">
                            <TrendingUp className="h-5 w-5 text-primary" />
                            Skill Breakdown
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {Object.entries(scorecard.skill_breakdown).map(([key, data]) => (
                            <div key={key} className="space-y-3">
                                <div className="flex justify-between items-center">
                                    <div className="flex items-center gap-2">
                                        <span className="font-bold capitalize text-base">
                                            {key.replace(/([A-Z])/g, ' $1').trim()}
                                        </span>
                                        <Badge variant="secondary" className="rounded-full text-[10px] h-5 px-2 bg-muted/50 border-none">
                                            {data.level}
                                        </Badge>
                                    </div>
                                    <span className={`font-black text-sm ${getScoreColor(data.score)}`}>
                                        {data.score}%
                                    </span>
                                </div>
                                <Progress value={data.score} className="h-1.5" />
                                <p className="text-sm text-muted-foreground leading-relaxed">{data.evidence}</p>
                            </div>
                        ))}
                    </CardContent>
                </Card>

                {/* Technologies */}
                <Card>
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-2 text-xl">
                            <Lightbulb className="h-5 w-5 text-primary" />
                            Technologies Analyzed
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {scorecard.technologies_known.map((tech) => (
                            <div key={tech.name} className="p-4 rounded-xl border border-border/50 bg-muted/5 space-y-2 hover:bg-muted/10 transition-colors cursor-default">
                                <div className="flex justify-between items-center">
                                    <span className="font-bold">{tech.name}</span>
                                    <Badge className="rounded-full bg-primary text-[10px] h-5 px-2 border-none">{tech.proficiency}</Badge>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Progress value={tech.percentage} className="h-1 flex-1" />
                                    <span className="text-[10px] font-black opacity-50">{tech.percentage}%</span>
                                </div>
                                <p className="text-xs text-muted-foreground line-clamp-2">{tech.evidence}</p>
                            </div>
                        ))}
                    </CardContent>
                </Card>

                {/* Skill Gaps */}
                <Card>
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-2 text-xl">
                            <AlertTriangle className="h-5 w-5 text-primary" />
                            Skill Gaps
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {scorecard.skill_gaps.map((gap, idx) => (
                            <div key={idx} className="space-y-3 p-4 rounded-xl bg-orange-500/5 border border-orange-500/10">
                                <div className="flex items-start justify-between">
                                    <h4 className="font-bold text-base">{gap.skill}</h4>
                                    <Badge variant={getPriorityColor(gap.priority)} className="rounded-full text-[10px] border-none uppercase tracking-tighter">
                                        {gap.priority}
                                    </Badge>
                                </div>
                                <p className="text-sm text-muted-foreground leading-relaxed italic">&quot;{gap.reason}&quot;</p>

                                <div className="space-y-2 pt-2">
                                    <div className="flex gap-2 items-start">
                                        <div className="h-5 w-5 rounded-full bg-orange-500/10 flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">1</div>
                                        <p className="text-sm"><span className="font-bold">Start:</span> {gap.learningPath.beginner}</p>
                                    </div>
                                    <div className="flex gap-2 items-start">
                                        <div className="h-5 w-5 rounded-full bg-orange-500/10 flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">2</div>
                                        <p className="text-sm"><span className="font-bold">Scale:</span> {gap.learningPath.intermediate}</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </CardContent>
                </Card>

                {/* Recommendations */}
                <Card className="bg-foreground text-background">
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-2 text-xl text-background">
                            <ArrowUpRight className="h-5 w-5" />
                            AI Roadmap
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <ul className="space-y-3">
                            {scorecard.recommendations.map((rec, idx) => (
                                <li key={idx} className="flex items-start gap-3">
                                    <CheckCircle2 className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                                    <span className="text-sm font-medium">{rec}</span>
                                </li>
                            ))}
                        </ul>
                    </CardContent>
                </Card>

                {/* Strengths & Improvements Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pb-12">
                    <div className="p-6 rounded-2xl bg-green-500/5 border border-green-500/10 space-y-4">
                        <h3 className="font-black text-green-500 flex items-center gap-2 italic tracking-tighter uppercase">✨ Strengths</h3>
                        <ul className="space-y-2">
                            {scorecard.strengths.map((s, i) => (
                                <li key={i} className="text-sm font-medium flex gap-2">
                                    <span className="text-green-500">✓</span> {s}
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div className="p-6 rounded-2xl bg-orange-500/5 border border-orange-500/10 space-y-4">
                        <h3 className="font-black text-orange-500 flex items-center gap-2 italic tracking-tighter uppercase">📈 Improve</h3>
                        <ul className="space-y-2">
                            {scorecard.areas_for_improvement.map((a, i) => (
                                <li key={i} className="text-sm font-medium flex gap-2">
                                    <span className="text-orange-500">→</span> {a}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
}
