-- Migration 003: Communities and Chat
-- Unified communities schema with correct columns.

-- 1. Communities Table
CREATE TABLE IF NOT EXISTS public.communities (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  tags TEXT, -- Unified column name
  creator_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Community Members
CREATE TABLE IF NOT EXISTS public.community_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(community_id, user_id)
);

-- 3. Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  reply_to_id BIGINT REFERENCES public.messages(id) ON DELETE SET NULL,
  attachments JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access to all users" ON public.communities;
CREATE POLICY "Allow read access to all users" ON public.communities FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Allow authenticated users to create communities" ON public.communities;
CREATE POLICY "Allow authenticated users to create communities" ON public.communities
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow authenticated users to join" ON public.community_members;
CREATE POLICY "Allow authenticated users to join" ON public.community_members 
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow everyone to view members" ON public.community_members;
CREATE POLICY "Allow everyone to view members" ON public.community_members FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Allow members to read messages" ON public.messages;
CREATE POLICY "Allow members to read messages" ON public.messages FOR SELECT USING (TRUE); -- Simplified for public communities

DROP POLICY IF EXISTS "Allow members to send messages" ON public.messages;
CREATE POLICY "Allow members to send messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Trigger for update
DROP TRIGGER IF EXISTS update_communities_updated_at ON public.communities;
CREATE TRIGGER update_communities_updated_at BEFORE UPDATE ON public.communities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
