-- MASTER SCHEMA PART 4: Communities & Chat
-- Setup for community groups, persistent chat, and file storage.

-- 1. Communities Table
CREATE TABLE IF NOT EXISTS public.communities (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  tags TEXT,
  creator_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Community Members (Joined)
CREATE TABLE IF NOT EXISTS public.community_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(community_id, user_id)
);

-- 3. Community Follows (Lurking)
CREATE TABLE IF NOT EXISTS public.community_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  followed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, community_id)
);

-- 4. Messages (Chat)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  attachments JSONB DEFAULT '[]'::JSONB,
  reply_to_id BIGINT REFERENCES public.messages(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. RLS Configuration
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Communities Policies
DROP POLICY IF EXISTS "Public Read Communities" ON public.communities;
CREATE POLICY "Public Read Communities" ON public.communities FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth Create Communities" ON public.communities;
CREATE POLICY "Auth Create Communities" ON public.communities FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Members & Follows Policies
DROP POLICY IF EXISTS "Public View Members" ON public.community_members;
CREATE POLICY "Public View Members" ON public.community_members FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can join communities" ON public.community_members;
CREATE POLICY "Users can join communities" ON public.community_members FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Public View Follows" ON public.community_follows;
CREATE POLICY "Public View Follows" ON public.community_follows FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can follow" ON public.community_follows;
CREATE POLICY "Users can follow" ON public.community_follows FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can unfollow" ON public.community_follows;
CREATE POLICY "Users can unfollow" ON public.community_follows FOR DELETE USING (auth.uid() = user_id);

-- Messages Policies
DROP POLICY IF EXISTS "Public Read Messages" ON public.messages;
CREATE POLICY "Public Read Messages" ON public.messages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth Send Messages" ON public.messages;
CREATE POLICY "Auth Send Messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Storage Setup (Communities Bucket)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('communities', 'communities', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Storage Public Access" ON storage.objects;
CREATE POLICY "Storage Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'communities');
DROP POLICY IF EXISTS "Storage Auth Upload" ON storage.objects;
CREATE POLICY "Storage Auth Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'communities' AND auth.role() = 'authenticated');

-- 7. Realtime Configuration
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
    END IF;
END $$;

-- 8. Triggers for updates
DROP TRIGGER IF EXISTS update_communities_updated_at ON public.communities;
CREATE TRIGGER update_communities_updated_at BEFORE UPDATE ON public.communities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
