-- Create communities table
create table if not exists public.communities (
  id uuid default gen_random_uuid() primary key,
  name text not null unique,
  description text,
  tags text, -- e.g. "Public", "Invite", "Private"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create community_members table
create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  community_id uuid references public.communities(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(community_id, user_id)
);

-- Create messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  community_id uuid references public.communities(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  content text not null,
  reply_to_id bigint references public.messages(id) on delete set null,
  attachments jsonb default '[]'::jsonb, -- Store URLs to images/files
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Simplified for prototype)
alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.messages enable row level security;

-- Allow read access to everyone for public communities
create policy "Allow read access to all users" on public.communities for select using (true);

-- Allow authenticated users to create communities
create policy "Allow authenticated users to create communities" on public.communities for insert with check (auth.role() = 'authenticated');

-- Allow authenticated users to join
create policy "Allow authenticated users to insert members" on public.community_members for insert with check (auth.uid() = user_id);
create policy "Allow members to view members" on public.community_members for select using (true);

-- Allow members to read messages
create policy "Allow members to read messages" on public.messages for select using (
  exists (
    select 1 from public.community_members
    where community_id = messages.community_id
    and user_id = auth.uid()
  )
);

-- Allow members to insert messages
create policy "Allow members to send messages" on public.messages for insert with check (
  exists (
    select 1 from public.community_members
    where community_id = messages.community_id
    and user_id = auth.uid()
  )
);
