-- Migration 007: Community Follows
-- Add ability to follow communities without joining

CREATE TABLE IF NOT EXISTS public.community_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
  followed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, community_id)
);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_community_follows_user_id ON public.community_follows(user_id);
CREATE INDEX IF NOT EXISTS idx_community_follows_community_id ON public.community_follows(community_id);

-- Enable RLS
ALTER TABLE public.community_follows ENABLE ROW LEVEL SECURITY;

-- Allow users to view follows
DROP POLICY IF EXISTS "Users can view follows" ON public.community_follows;
CREATE POLICY "Users can view follows" ON public.community_follows
  FOR SELECT USING (TRUE);

-- Allow users to follow communities
DROP POLICY IF EXISTS "Users can follow communities" ON public.community_follows;
CREATE POLICY "Users can follow communities" ON public.community_follows
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Allow users to unfollow communities
DROP POLICY IF EXISTS "Users can unfollow communities" ON public.community_follows;
CREATE POLICY "Users can unfollow communities" ON public.community_follows
  FOR DELETE USING (auth.uid() = user_id);
