-- Standardize communities table
DO $$ 
BEGIN 
    -- Add tags if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='communities' AND column_name='tags') THEN
        ALTER TABLE public.communities ADD COLUMN tags TEXT;
    END IF;

    -- Add creator_id if missing (from migration 003) or make it optional
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='communities' AND column_name='creator_id') THEN
        ALTER TABLE public.communities ADD COLUMN creator_id UUID REFERENCES public.users(id) ON DELETE CASCADE;
    ELSE
        ALTER TABLE public.communities ALTER COLUMN creator_id DROP NOT NULL;
    END IF;

    -- Ensure community_members table exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='community_members') THEN
        CREATE TABLE public.community_members (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            community_id UUID REFERENCES public.communities(id) ON DELETE CASCADE NOT NULL,
            user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
            joined_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE(community_id, user_id)
        );
    END IF;
END $$;

-- Update RLS for easier creation during prototype
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can create communities." ON public.communities;
DROP POLICY IF EXISTS "Allow authenticated users to create communities" ON public.communities;
DROP POLICY IF EXISTS "Allow read access to all users" ON public.communities;
DROP POLICY IF EXISTS "Public communities are viewable by all." ON public.communities;

CREATE POLICY "Allow read access to all users" ON public.communities FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to create communities" ON public.communities
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow authenticated users to insert members" ON public.community_members;
DROP POLICY IF EXISTS "Allow members to view members" ON public.community_members;

CREATE POLICY "Allow authenticated users to join" ON public.community_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow members to view members" ON public.community_members FOR SELECT USING (true);
